### ISSUE TITLE
Missing access_token?

### ISSUE THREAD

**Issue by Kiina** [robertklep/node-trakt-api#10]
Most of the stuff seems to work fine but `calendarMyShowsNew, calendarMyShowsPremieres and calendarMyMovies` always return 401. From what I can tell in the documentation you need OAuth and an valid OAuth access_token which seems to be not supported by this module. Am I missing something or do these methods just not work in the current form?

**Comment by robertklep** [comment]
Yeah, I'm afraid all endpoints that require OAuth2 are not supported.

There are probably better modules to use, for example [`trakt.tv`](https://github.com/vankasteelj/trakt.tv).

I'll start considering deprecating this one, as I don't have the time to update it.
