### ISSUE TITLE
Search filtered by year

### ISSUE THREAD

**Issue by ocombe** [robertklep/node-trakt-api#3]
Hello,

is this possible to add the search param "year" as specified in [the API](http://docs.trakt.apiary.io/reference/search) ?

> You can optionally limit the type of results to return. Send a comma separated string to get results for multiple types. You can optionally filter the **year** for movie and show results.

I can make a PR if necessary.

**Comment by robertklep** [comment]
@ocombe I just pushed `0.3.0` which added an optional `year` parameter (as integer) to the search methods 😀(via 9f87cdfd92eb7ef0b44a5f7651b789cf017a6b88)

**Comment by ocombe** [comment]
Awesome, thanks for doing this so fast! :)

**Comment by robertklep** [comment]
@ocombe no problem! It was an easy fix and something I overlooked in the API docs to begin with.

**Comment by ocombe** [comment]
Yep, I had this problem with the show "The player", it returned an old tv show instead of the new one from 2015, unless you specify the year

**Comment by robertklep** [comment]
@ocombe do you pick the first search result returned? _"The Player (2015)"_ shows up in the results when you search for "the player", just not on the first spot. BTW cool show 😉

**Comment by ocombe** [comment]
yeah, I pick the first result by default, but the user will be able to change it afterwards

**Comment by ocombe** [comment]
One think that I don't like in the trackt API is that if you search for `The Player (2015)` (which is in fact the name of the show that I detected) it doesn't return anything, you have to strip the year out and then you don't get the good show as the first result (unless you put it back into the "year" field)

**Comment by robertklep** [comment]
@ocombe I just noticed that searching for the Trakt id (`the-player-2015`) also doesn't yield any results, which is a bit unexpected (although perhaps a bit moot, because why would anyone search for a Trakt ID instead of just retrieving the show details using that id directly).

**Comment by ocombe** [comment]
It works fine, but the year has to be a number, you might want to say it in the docs because I lost some time trying to figure out why it wouldn't work with "2015" until I tried with a number :)

**Comment by robertklep** [comment]
Good point, I'll update the README.
