### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by ghost** [robertklep/node-trakt-api#4]
Hi,
I use your node module to search some films and series, but i need to access to the calendar. Not all function of api calendar, just two urls :
- [calendars/all/show](http://docs.trakt.apiary.io/#reference/calendars/all-shows/get-shows)
- And the same for movies [calendars/all/movies](http://docs.trakt.apiary.io/#reference/calendars/all-movies/get-movies)

I saw that this features are not implemented, How I can access to this features ?

**Comment by robertklep** [comment]
@oema they look to be trivial to implement, let me take a look.

**Comment by robertklep** [comment]
@oema implemented with 992d9c5, I'll push an update after I take a look at #5 😀)

**Comment by ghost** [comment]
Thank a lot
